# Generated by Django 6.0.5 on 2026-05-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_email_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(blank=True, null=True, verbose_name="Токен подтверждения email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="reset_password_token",
            field=models.UUIDField(blank=True, null=True, verbose_name="Токен сброса пароля"),
        ),
        migrations.AlterField(
            model_name="user",
            name="reset_password_token_created_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время создания токена сброса"),
        ),
    ]
