services:
  web:
    image: ${{ secrets.DOCKER_USERNAME }}/diploma:latest
    container_name: docsearch_web
    ports:
      - "8001:8000"
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py search_index --rebuild -f &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --access-logfile - --error-logfile -
      "
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=${DEBUG:-False}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL:-redis://host.docker.internal:6379/0}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: docker-nginx_web-network  # Сеть от основного Nginx (с Nextcloud)
