[tool.poetry]
name = "document-search"
version = "0.1.0"
description = "Полнотекстовый поиск документов с Elasticsearch"
authors = ["Aleksey Lozhkin <aleksey.s.lozhkin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
django = ">=6.0.5,<7.0.0"
djangorestframework = ">=3.17.1,<4.0.0"
djangorestframework-simplejwt = ">=5.5.1,<6.0.0"
psycopg2-binary = ">=2.9.12,<3.0.0"
django-elasticsearch-dsl = "7.4.0"
drf-yasg = ">=1.21.15,<2.0.0"
python-dotenv = ">=1.2.2,<2.0.0"
gunicorn = ">=26.0.0,<27.0.0"
django-htmx = ">=1.27.0,<2.0.0"
requests = "^2.34.2"
django-redis = "^6.0.0"
python-docx = "^1.2.0"
openpyxl = "^3.1.5"
django-ratelimit = "^4.1.0"
pdfplumber = "^0.11.9"
pypdf = "^6.12.1"
elasticsearch-dsl = ">=7.2.0,<8.0.0"
django-verify-email = "^3.0.3"
uuid = "^1.30"
virtualenv = "20.39.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
pytest-django = "^4.5"
pytest-cov = "^4.1"
flake8 = "^6.1"
black = "^23.11"
isort = "^5.12"
pre-commit = "^3.5"
djangorestframework-stubs = "^3.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = "test_*.py"
addopts = "--cov=documents --cov-report=html --cov-report=term"
