# Generated by Django 6.0.5 on 2026-05-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rubrics", models.JSONField(default=list)),
                ("text", models.TextField(verbose_name="Текст документа")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичный документ")),
                ("file", models.FileField(blank=True, null=True, upload_to="documents/%Y/%m/%d/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=20)),
                (
                    "text_source",
                    models.CharField(
                        choices=[("file", "Из загруженного файла"), ("manual", "Ручной ввод")],
                        default="manual",
                        max_length=10,
                        verbose_name="Источник текста",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=500)),
                ("results_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
