# Generated by Django 6.0.5 on 2026-10-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Кому выдан")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("personal", "От имени человека: свои и публичные документы"),
                            ("service", "Служебный: только публичные документы"),
                        ],
                        default="service",
                        max_length=10,
                    ),
                ),
                ("prefix", models.CharField(max_length=16, verbose_name="Начало значения")),
                ("key_hash", models.CharField(max_length=64, unique=True, verbose_name="Хеш значения")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Действует")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен потребителя",
                "verbose_name_plural": "Токены потребителей",
                "ordering": ["-created_at"],
            },
        ),
    ]
