# Generated by Django 6.0.5 on 2026-05-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_document_file_document_file_name_document_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="text_source",
            field=models.CharField(
                choices=[("file", "Из загруженного файла"), ("manual", "Ручной ввод")],
                default="manual",
                max_length=10,
                verbose_name="Источник текста",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="text",
            field=models.TextField(verbose_name="Текст документа"),
        ),
    ]
