# Generated by Django 6.0.5 on 2026-10-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="keywords",
            field=models.JSONField(blank=True, default=list, verbose_name="Теги"),
        ),
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
    ]
