# Generated by Django 6.0.5 on 2026-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичный документ"),
        ),
        migrations.AlterField(
            model_name="document",
            name="text",
            field=models.TextField(verbose_name="Текст документа (HTML)"),
        ),
    ]
